- src/main/groovy/com/metalr2/butler/model/release/ReleaseEntity.groovy
We had the standard length of 255 chars ont the url columns. We had one example that exceeded this. So URLs saved to the database can now be up to 500 characters long.
> Bug - URL too long

- build.gradle
- src/main/groovy/rocks/metaldetector/butler/web/rest/ReleasesRestController.groovy
- src/test/groovy/rocks/metaldetector/butler/web/rest/ReleasesRestControllerIT.groovy
All our dependencies are now up to date.
There were some issues with groovy-all (groovy 2.5.x was loaded, but 3.0.2 defined in gradle) so I had to import all the groovy modules separately. I guess it's SETT and we just check later if '-all' works again. Also I threw out the RestAssured dependency as I didn't manage to get it running in the Integration Test and just used MockMvc instead.
> Dependency updates

- src/main/groovy/rocks/metaldetector/butler/config/web/RestTemplateConfig.groovy
- src/main/groovy/rocks/metaldetector/butler/service/ReleaseServiceImpl.groovy
- src/main/groovy/rocks/metaldetector/butler/web/dto/ReleaseDto.groovy
- src/test/groovy/rocks/metaldetector/butler/DtoFactory.groovy
I just mapped everything we have and we'll see what we show in the Detector.
I also configrued the ObjectMapper in our RestTemplate to serialize empty lists. This fixed an NPE in the response trafo in the Detector when the releases table is empty.
> All release infos sent

- src/main/groovy/rocks/metaldetector/butler/web/dto/ReleasesRequestPaginated.groovy
- src/test/groovy/rocks/metaldetector/butler/web/rest/ReleasesRestControllerTest.groovy
I implemented a validation method inside the `ReleasesRequestPaginated` class. This is kind of the "easy way out" instead of implementing a custom validator with annotations. I tried that but there were some issues with groovy. It seems not to be possible to define an inner annotation class inside an annotation. This was needed in the example (see [here](https://stackoverflow.com/questions/1972933/cross-field-validation-with-hibernate-validator-jsr-303)) . In Java it works, I've tried it in the Detector.
I think this is GEFN :)
> dateFrom has to be equal to or earlier than dateTo

- .github/workflows/docker-image.yml
- src/main/groovy/rocks/metaldetector/butler/config/AppConfig.groovy
- src/main/groovy/rocks/metaldetector/butler/config/constants/Endpoints.groovy
- src/main/groovy/rocks/metaldetector/butler/model/importjob/ImportJobEntity.groovy
- src/main/groovy/rocks/metaldetector/butler/model/importjob/ImportJobRepository.groovy
- src/main/groovy/rocks/metaldetector/butler/model/release/ReleaseEntity.groovy
- src/main/groovy/rocks/metaldetector/butler/model/release/ReleaseRepository.groovy
- src/main/groovy/rocks/metaldetector/butler/service/cover/MetalArchivesCoverFetcher.groovy
- src/main/groovy/rocks/metaldetector/butler/service/release/MetalArchivesReleaseImportService.groovy
- src/main/groovy/rocks/metaldetector/butler/service/release/MetalHammerReleaseImportService.groovy
- src/main/groovy/rocks/metaldetector/butler/service/release/ReleaseImportService.groovy
- src/main/groovy/rocks/metaldetector/butler/service/release/ReleaseService.groovy
- src/main/groovy/rocks/metaldetector/butler/service/release/ReleaseServiceImpl.groovy
- src/main/groovy/rocks/metaldetector/butler/service/transformer/ImportJobTransformer.groovy
- src/main/groovy/rocks/metaldetector/butler/web/dto/CreateImportJobResponse.groovy
- src/main/groovy/rocks/metaldetector/butler/web/dto/ImportJobResponse.groovy
- src/main/groovy/rocks/metaldetector/butler/web/rest/ReleasesRestController.groovy
- src/main/resources/application-preview.yml
- src/main/resources/application-prod.yml
- src/test/groovy/rocks/metaldetector/butler/model/release/ReleaseEntityTest.groovy
- src/test/groovy/rocks/metaldetector/butler/service/release/MetalArchivesReleaseImportServiceTest.groovy
- src/test/groovy/rocks/metaldetector/butler/service/release/ReleaseServiceTest.groovy
- src/test/groovy/rocks/metaldetector/butler/service/transformer/ImportJobTransformerTest.groovy
- src/test/groovy/rocks/metaldetector/butler/web/rest/ReleasesRestControllerIT.groovy
- src/test/groovy/rocks/metaldetector/butler/web/rest/ReleasesRestControllerTest.groovy
The import job endpoint now responds very quickly with a job id. The whole import process is made asynchronously.
The next step is to fetch all import job results so we can have a look at it from our admin area.
> Create import job asynchronously

- build.gradle
Update of Spring Boot, Groovy and Spock. 
I was able to remove the single groovy imports with groovy-all by just forcing the new version. I also had to exclude testng because the currently used new version in groovy 3.0.4 is not yet present on maven central. We could get it from jcenter but at we don't use it anyways it's cleaner to exclude I think. More info on that [here](https://groovy-lang.org/releasenotes/groovy-3.0.html), search for `testng`.
Some other dependencies also had to be forced.
> Dependency update and cleanup

- src/main/groovy/rocks/metaldetector/butler/service/cover/CoverServiceImpl.groovy
- src/test/groovy/rocks/metaldetector/butler/service/cover/CoverServiceImplTest.groovy
The CoverService now checks the source url for null.
> Nullsafety for cover download

- src/main/groovy/rocks/metaldetector/butler/model/release/ReleaseRepository.groovy
- src/main/groovy/rocks/metaldetector/butler/service/release/PageTransformer.groovy
- src/main/groovy/rocks/metaldetector/butler/service/release/ReleaseService.groovy
- src/main/groovy/rocks/metaldetector/butler/service/release/ReleaseServiceImpl.groovy
- src/main/groovy/rocks/metaldetector/butler/service/release/ReleasesResponseTransformer.groovy
- src/main/groovy/rocks/metaldetector/butler/web/api/ErrorResponse.groovy
- src/main/groovy/rocks/metaldetector/butler/web/api/ImportJobResponse.groovy
- src/main/groovy/rocks/metaldetector/butler/web/api/Pagination.groovy
- src/main/groovy/rocks/metaldetector/butler/web/api/ReleasesRequest.groovy
- src/main/groovy/rocks/metaldetector/butler/web/api/ReleasesRequestPaginated.groovy
- src/main/groovy/rocks/metaldetector/butler/web/api/ReleasesResponse.groovy
- src/main/groovy/rocks/metaldetector/butler/web/rest/ImportJobRestController.groovy
- src/main/groovy/rocks/metaldetector/butler/web/rest/ReleasesRestController.groovy
- src/main/groovy/rocks/metaldetector/butler/web/rest/RestExceptionHandler.groovy
- src/test/groovy/rocks/metaldetector/butler/DtoFactory.groovy
- src/test/groovy/rocks/metaldetector/butler/service/importjob/MetalArchivesReleaseImporterTest.groovy
- src/test/groovy/rocks/metaldetector/butler/service/importjob/MetalHammerReleaseImporterTest.groovy
- src/test/groovy/rocks/metaldetector/butler/service/importjob/PersistReleaseEntityTaskTest.groovy
- src/test/groovy/rocks/metaldetector/butler/service/release/PageTransformerTest.groovy
- src/test/groovy/rocks/metaldetector/butler/service/release/ReleaseServiceImplTest.groovy
- src/test/groovy/rocks/metaldetector/butler/service/release/ReleasesResponseTransformerTest.groovy
- src/test/groovy/rocks/metaldetector/butler/web/rest/ImportJobRestControllerTest.groovy
- src/test/groovy/rocks/metaldetector/butler/web/rest/ReleasesRestControllerIT.groovy
- src/test/groovy/rocks/metaldetector/butler/web/rest/ReleasesRestControllerTest.groovy
We already got one `Page` back from the Spring Data Repository. The `Page` contains all relevant pagination information. Therefore I removed the `countXXX` methods and did some other refactorings.
> Refactor pagination handling

- Dockerfile
- src/main/groovy/rocks/metaldetector/butler/service/release/ReleaseService.groovy
- src/main/groovy/rocks/metaldetector/butler/service/release/ReleaseServiceImpl.groovy
- src/main/groovy/rocks/metaldetector/butler/web/rest/ReleasesRestController.groovy
- src/test/groovy/rocks/metaldetector/butler/service/release/ReleaseServiceImplTest.groovy
- src/test/groovy/rocks/metaldetector/butler/web/rest/ReleasesRestControllerTest.groovy
All endpoints for releases now can be called with a sorting parameter. The default stays as is.
> Sorting for releases endpoints

- src/main/groovy/rocks/metaldetector/butler/service/cover/S3PersistenceService.groovy
- src/test/groovy/rocks/metaldetector/butler/service/cover/S3PersistenceServiceTest.groovy
If a `FileNotFoundException` occurs, the upload of the cover should be skipped. 
All other exceptions are handled by the `ReleaseImporter` and the import is evaluated as `ERROR`.
This might not be the final solution yet. I want to see how we can minimize the noise in Slack.
> rework s3 upload exception handling

- Dockerfile
- docker-compose.yml
- docker-entrypoint.sh
- src/main/groovy/rocks/metaldetector/butler/service/converter/TimeForMetalReleaseEntityConverter.groovy
- src/test/groovy/rocks/metaldetector/butler/service/converter/TimeForMetalReleaseEntityConverterTest.groovy
Docker Swarm manages the secrets encrypted on the host. If a container shall use a secret, docker mounts it via a file in the container. The container must therefore be smart enough to set an ENV from the contents of a file. This is now done by the new `docker-entrypoint.sh` that is copied into the docker image. 
For example, `docker run` can be executed as follows:
```bash
docker run -e JWT_SECRET=my-secret metaldetector/metal-release-butler
```
We already know that.
Now, also possible is:
```bash
docker run -e JWT_SECRET_FILE=/path/to/secret metaldetector/metal-release-butler
```
The last variant will expose the contents of the file to the ENV `JWT_SECRET`.
> prepare for docker swarm

- src/main/groovy/rocks/metaldetector/butler/service/converter/TimeForMetalReleaseEntityConverter.groovy
- src/test/groovy/rocks/metaldetector/butler/service/converter/TimeForMetalReleaseEntityConverterTest.groovy
Currently all EP's album titles from TimeForMetal ended with "Title ()". The problem was the use of replaceAll instead of replace. replaceAll takes a regex as first parameter and not a char sequence.
> Time For Metal Converter album title bug with EPs fixed

- .github/workflows/docker-image.yml
- Dockerfile
- src/main/resources/application-preview.yml
- src/main/resources/application-prod.yml
- src/main/resources/application.yml
The path for the healthcheck must be specified directly in the Dockerfile. A placeholder mechanism does not work here. 
Therefore, we now work without obfuscation for the `/health` endpoint. The endpoints `/info`, `/metrics`, `/prometheus` and `/flyway` will hide behind an obfuscated URL.
> improve docker healthcheck

- src/main/groovy/rocks/metaldetector/butler/service/importjob/MetalArchivesReissueTask.groovy
If the document is null (or anything in it), null-items cannot be substracted, so a nullsafe findAll is better here.
> Fix npe in MetalArchivesReissueTask

- Dockerfile
The docker build fails currently. Could you please take a look at lines 18 and 41 in the dockerfile? Do we have to adjust these paths too? I'm a bit confused that the "app" segment already exists there 🤔
> Fix path to jars in Dockerfile

- docker-compose.yml
IntelliJ complains about the restart policy. 
I also decided to use some kind of namespace for the volumes here, because volumes with the same naming are also created by the Detector and sharing them is not so easy.
> rework restart policy and use 'butler' namespace for volumes

- app/src/main/groovy/rocks/metaldetector/butler/config/security/SecurityConfig.groovy
The `ReleaseCoverRestController` is only used on default profile and returns the image from local filesystem as multimedia resource. The frontend directly calls for example `http://butler.com/rest/v1/releases/image/1234-1234-1234-1234` in img src. 
I thought about creating a separate SecurityConfig for the default profile as well, but that was too over-engineered for a single endpoint that is only available locally
> allow anonymous access on local release image endpoint

- .github/workflows/ci.yml
- .github/workflows/docker-image.yml
Currently CI (= clean build) runs on push to master and on PR. The docker task (= clean bootJar, so no tests) runs on push to master. If we want to have all tests run after pushing to master (which I think makes sense) it sounds smarter to me to run the clean build when building the docker image (instead of using only bootJar). If anything fails, then building the image would fail and it would not be pushed to docker hub. This way we are sure that all tests are run if for example for whatever reason code is pushed to master without a PR.
> Better config for github workflows

- app/src/main/groovy/rocks/metaldetector/butler/config/swagger/SwaggerConfig.groovy
- app/src/main/groovy/rocks/metaldetector/butler/config/web/ResourceNotFoundException.groovy
- app/src/main/groovy/rocks/metaldetector/butler/config/web/WebMvcConfig.groovy
- app/src/main/groovy/rocks/metaldetector/butler/service/release/ImageResourceFinder.groovy
- app/src/main/groovy/rocks/metaldetector/butler/service/release/ReleaseServiceImpl.groovy
- app/src/main/groovy/rocks/metaldetector/butler/web/api/ReleasesRequest.groovy
- app/src/main/groovy/rocks/metaldetector/butler/web/api/ReleasesRequestPaginated.groovy
- app/src/main/groovy/rocks/metaldetector/butler/web/rest/ReleaseCoverRestController.groovy
- app/src/main/groovy/rocks/metaldetector/butler/web/rest/ReleasesRestController.groovy
- app/src/main/groovy/rocks/metaldetector/butler/web/rest/RestExceptionHandler.groovy
- app/src/test/groovy/rocks/metaldetector/butler/service/release/ImageResourceFinderTest.groovy
- app/src/test/groovy/rocks/metaldetector/butler/service/release/ReleaseServiceImplTest.groovy
- app/src/test/groovy/rocks/metaldetector/butler/testutil/WithIntegrationTestConfig.groovy
- app/src/test/groovy/rocks/metaldetector/butler/web/api/ReleasesRequestTest.groovy
- app/src/test/groovy/rocks/metaldetector/butler/web/rest/ImportJobRestControllerIT.groovy
- app/src/test/groovy/rocks/metaldetector/butler/web/rest/ImportJobRestControllerTest.groovy
- app/src/test/groovy/rocks/metaldetector/butler/web/rest/ReleaseCoverRestControllerIT.groovy
- app/src/test/groovy/rocks/metaldetector/butler/web/rest/ReleaseCoverRestControllerTest.groovy
- app/src/test/groovy/rocks/metaldetector/butler/web/rest/ReleasesRestControllerIT.groovy
- app/src/test/groovy/rocks/metaldetector/butler/web/rest/ReleasesRestControllerSecurityIT.groovy
- app/src/test/groovy/rocks/metaldetector/butler/web/rest/ReleasesRestControllerTest.groovy
- app/src/test/groovy/rocks/metaldetector/butler/web/rest/RestExceptionHandlerIT.groovy
- supplier/infrastructure/src/main/groovy/rocks/metaldetector/butler/supplier/infrastructure/cover/LocalCoverPersistenceService.groovy
- supplier/infrastructure/src/test/groovy/rocks/metaldetector/butler/supplier/infrastructure/cover/LocalCoverPersistenceServiceTest.groovy
- supplier/infrastructure/src/test/groovy/rocks/metaldetector/butler/supplier/infrastructure/cover/LocalFileTransferServiceTest.groovy
- supplier/infrastructure/src/test/groovy/rocks/metaldetector/butler/supplier/infrastructure/cover/S3PersistenceServiceTest.groovy
This started with me wanting to improve code coverage a bit and ended with rewriting our api error handling 😅 
We often did not use Bad Request vs. Unprosessable Entity correctly. Also the RestExceptionHandler was not used correctly everywhere and the IllegalArgumentException we used in some placed should really be a custom ResourceNotFound (like in the Detector).
A bigger question mark stays with the `ReleaseCoverRestController` for me... I had the feeling that it is not really working the way I expected for a while, but latest with the switch to OAuth something is off.. I always get a "Full Authentication required" message when trying to access images. Which makes sense as it is configured that way in the `SecurityConfig`. There is even a token sent, but that is the Detector's token …
> Improved HttpStatus on errors and overall code coverage

- app/src/main/groovy/rocks/metaldetector/butler/config/security/SecurityConfig.groovy
- app/src/main/groovy/rocks/metaldetector/butler/service/statistics/StatisticsService.groovy
- app/src/main/groovy/rocks/metaldetector/butler/web/api/ReleaseInfo.groovy
- app/src/main/groovy/rocks/metaldetector/butler/web/api/StatisticsResponse.groovy
- app/src/main/groovy/rocks/metaldetector/butler/web/rest/StatisticsRestController.groovy
- app/src/test/groovy/rocks/metaldetector/butler/service/statistics/StatisticsServiceTest.groovy
- app/src/test/groovy/rocks/metaldetector/butler/web/rest/StatisticsRestControllerSecurityIntegrationTest.groovy
- app/src/test/groovy/rocks/metaldetector/butler/web/rest/StatisticsRestControllerTest.groovy
- persistence/src/main/groovy/rocks/metaldetector/butler/persistence/domain/release/ReleasePerMonth.groovy
- persistence/src/main/groovy/rocks/metaldetector/butler/persistence/domain/release/ReleaseRepository.groovy
- persistence/src/test/groovy/rocks/metaldetector/butler/persistence/domain/release/ReleaseRepositoryIntegrationTest.groovy
- supplier/infrastructure/src/main/groovy/rocks/metaldetector/butler/supplier/infrastructure/Endpoints.groovy
I added a new scope (see [here](https://github.com/MetalDetectorRocks/metal-detector-auth/pull/169)) because it felt weird to use any of the existing ones.
> Endpoint for release statistics added

- app/src/main/resources/application.yml
- docker-compose.yml
- supplier/infrastructure/src/main/groovy/rocks/metaldetector/butler/supplier/infrastructure/importjob/AbstractReleaseImporter.groovy
- supplier/infrastructure/src/main/groovy/rocks/metaldetector/butler/supplier/infrastructure/importjob/CoverDownloadTask.groovy
- supplier/infrastructure/src/main/groovy/rocks/metaldetector/butler/supplier/infrastructure/importjob/ParallelCoverDownloader.groovy
- supplier/infrastructure/src/test/groovy/rocks/metaldetector/butler/supplier/infrastructure/importjob/AbstractReleaseImporterTest.groovy
- supplier/infrastructure/src/test/groovy/rocks/metaldetector/butler/supplier/infrastructure/importjob/CoverDownloadTaskTest.groovy
- supplier/infrastructure/src/test/groovy/rocks/metaldetector/butler/supplier/infrastructure/importjob/ParallelCoverDownloaderTest.groovy
- supplier/metal-archives/src/main/groovy/rocks/metaldetector/butler/supplier/metalarchives/MetalArchivesReleaseImportUtils.groovy
- supplier/metal-archives/src/main/groovy/rocks/metaldetector/butler/supplier/metalarchives/MetalArchivesReleaseVersionsWebCrawler.groovy
- supplier/metal-archives/src/main/groovy/rocks/metaldetector/butler/supplier/metalarchives/cover/MetalArchivesCoverFetcher.groovy
- supplier/metal-archives/src/main/groovy/rocks/metaldetector/butler/supplier/metalarchives/importjob/MetalArchivesReleaseImporter.groovy
- supplier/metal-archives/src/main/groovy/rocks/metaldetector/butler/supplier/metalarchives/importjob/ReissueHintEnhancer.groovy
- supplier/metal-archives/src/test/groovy/rocks/metaldetector/butler/supplier/metalarchives/importjob/MetalArchivesReleaseImporterTest.groovy
- supplier/metal-archives/src/test/groovy/rocks/metaldetector/butler/supplier/metalarchives/importjob/ReissueHintEnhancerTest.groovy
I have modified the Metal Archives import a bit so that individual batches are already saved. Then we are a bit more robust in case of an error. Currently, the entire import progress is discarded as soon as an error occurs.
> import in batches

- app/src/main/groovy/rocks/metaldetector/butler/config/security/SecurityConfig.groovy
- app/src/main/groovy/rocks/metaldetector/butler/service/importjob/ImportJobService.groovy
- app/src/main/groovy/rocks/metaldetector/butler/service/importjob/ImportJobTask.groovy
- app/src/main/groovy/rocks/metaldetector/butler/service/importjob/ImportJobTransformer.groovy
- app/src/main/groovy/rocks/metaldetector/butler/web/api/ImportJobCreatedResponse.groovy
- app/src/main/groovy/rocks/metaldetector/butler/web/dto/ImportJobDto.groovy
- app/src/main/groovy/rocks/metaldetector/butler/web/rest/ImportJobRestController.groovy
- app/src/main/resources/db/migration/v4_0__job_entity_update.sql
- app/src/test/groovy/rocks/metaldetector/butler/service/importjob/ImportJobServiceTest.groovy
- app/src/test/groovy/rocks/metaldetector/butler/service/importjob/ImportJobTaskTest.groovy
- app/src/test/groovy/rocks/metaldetector/butler/service/importjob/ImportJobTransformerTest.groovy
- app/src/test/groovy/rocks/metaldetector/butler/web/rest/ImportJobRestControllerIntegrationTest.groovy
- app/src/test/groovy/rocks/metaldetector/butler/web/rest/ImportJobRestControllerTest.groovy
- persistence/src/main/groovy/rocks/metaldetector/butler/persistence/domain/importjob/ImportJobEntity.groovy
- persistence/src/main/groovy/rocks/metaldetector/butler/persistence/domain/importjob/ImportJobRepository.groovy
- persistence/src/main/groovy/rocks/metaldetector/butler/persistence/domain/importjob/JobState.groovy
- persistence/src/test/groovy/rocks/metaldetector/butler/persistence/domain/importjob/ImportJobRepositoryIntegrationTest.groovy
- supplier/infrastructure/src/main/groovy/rocks/metaldetector/butler/supplier/infrastructure/Endpoints.groovy
- supplier/infrastructure/src/main/groovy/rocks/metaldetector/butler/supplier/infrastructure/config/InfrastructureConfig.groovy
- supplier/infrastructure/src/main/groovy/rocks/metaldetector/butler/supplier/infrastructure/importjob/AbstractReleaseImporter.groovy
Currently the import is kind of 'fake asynchron'. The controller returns fast but the jobs run chronologically and we have no means to check on them. So what I did is remove the @Async annotation on the service and instead schedule the imports in a new threadPoolExecutor. The method returns the job's Ids and with a new endpoint these IDs can be requested to check on the state of the jobs.
Parallel imports brings the problem that we have to synchronize writing and reading on the release repository. In this PR I'm going the easy way and simply synchronize the whole saving of the releases. That's easy and safe but we also loose a lot of the advantage of parallelizing the imports. I'll take a look at that later on, I think with some read and write locks we can improve this quite a bit, but …
> import jobs are scheduled and createJob endpoint returns job ids

- build.gradle.kts
- supplier/infrastructure/src/main/groovy/rocks/metaldetector/butler/supplier/infrastructure/config/SynchronicityConfig.groovy
- supplier/infrastructure/src/main/groovy/rocks/metaldetector/butler/supplier/infrastructure/importjob/AbstractReleaseImporter.groovy
- supplier/infrastructure/src/main/groovy/rocks/metaldetector/butler/supplier/infrastructure/importjob/ParallelCoverDownloader.groovy
- supplier/infrastructure/src/test/groovy/rocks/metaldetector/butler/supplier/infrastructure/importjob/AbstractReleaseImporterTest.groovy
- supplier/infrastructure/src/test/groovy/rocks/metaldetector/butler/supplier/infrastructure/importjob/ParallelCoverDownloaderTest.groovy
- supplier/metal-archives/src/main/groovy/rocks/metaldetector/butler/supplier/metalarchives/importjob/ReissueHintEnhancer.groovy
- supplier/metal-archives/src/test/groovy/rocks/metaldetector/butler/supplier/metalarchives/importjob/MetalArchivesReleaseImporterTest.groovy
- supplier/metal-archives/src/test/groovy/rocks/metaldetector/butler/supplier/metalarchives/importjob/ReissueHintEnhancerTest.groovy
- supplier/time-for-metal/src/test/groovy/rocks/metaldetector/butler/supplier/timeformetal/importjob/TimeForMetalReleaseImporterTest.groovy
To really leverage asynchronicity here I used ReadWrite-Locks to improve access to the ReleaseRepository. This does require more database communication but the time won through parallel work should be far more.
> Sync repository access

- .github/workflows/dependency-submission.yml
exclude detached configurations from dependency graph as they show vulnerabilities that are actually fixed in production code; see https://github.com/gradle/actions/issues/390
> fix false positive security issues
